name: AlgoliaSearchClient
targets:
  AlgoliaSearchClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources/AlgoliaSearchClient]
    info:
      path: ./Info.plist
      version: 9.0.0-alpha.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
